package hz.mall.flashsale.mapper;

import hz.mall.flashsale.domain.OrderDo;

public interface OrderDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Jul 27 17:14:07 EDT 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Jul 27 17:14:07 EDT 2022
     */
    int insert(OrderDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Jul 27 17:14:07 EDT 2022
     */
    int insertSelective(OrderDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Jul 27 17:14:07 EDT 2022
     */
    OrderDo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Jul 27 17:14:07 EDT 2022
     */
    int updateByPrimaryKeySelective(OrderDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Wed Jul 27 17:14:07 EDT 2022
     */
    int updateByPrimaryKey(OrderDo row);
}