package hz.mall.flashsale.mapper;

import hz.mall.flashsale.domain.SequenceDo;

public interface SequenceDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jul 27 18:37:16 EDT 2022
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jul 27 18:37:16 EDT 2022
     */
    int insert(SequenceDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jul 27 18:37:16 EDT 2022
     */
    int insertSelective(SequenceDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jul 27 18:37:16 EDT 2022
     */
    SequenceDo selectByPrimaryKey(String name);

    SequenceDo getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jul 27 18:37:16 EDT 2022
     */
    int updateByPrimaryKeySelective(SequenceDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jul 27 18:37:16 EDT 2022
     */
    int updateByPrimaryKey(SequenceDo row);
}