package hz.mall.flashsale.mapper;

import hz.mall.flashsale.domain.StockLogDo;

public interface StockLogDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Aug 09 22:14:28 EDT 2022
     */
    int deleteByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Aug 09 22:14:28 EDT 2022
     */
    int insert(StockLogDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Aug 09 22:14:28 EDT 2022
     */
    int insertSelective(StockLogDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Aug 09 22:14:28 EDT 2022
     */
    StockLogDo selectByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Aug 09 22:14:28 EDT 2022
     */
    int updateByPrimaryKeySelective(StockLogDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Tue Aug 09 22:14:28 EDT 2022
     */
    int updateByPrimaryKey(StockLogDo row);
}