package hz.mall.flashsale.mapper;

import hz.mall.flashsale.domain.UserPassword;
import org.springframework.stereotype.Repository;

public interface UserPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jul 24 16:21:19 EDT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jul 24 16:21:19 EDT 2022
     */
    int insert(UserPassword row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jul 24 16:21:19 EDT 2022
     */
    int insertSelective(UserPassword row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jul 24 16:21:19 EDT 2022
     */
    UserPassword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jul 24 16:21:19 EDT 2022
     */
    int updateByPrimaryKeySelective(UserPassword row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jul 24 16:21:19 EDT 2022
     */
    int updateByPrimaryKey(UserPassword row);
}