package hz.mall.flashsale.mapper;

import hz.mall.flashsale.domain.UserDo;
import org.springframework.stereotype.Component;

public interface UserDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Jul 24 18:33:43 EDT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Jul 24 18:33:43 EDT 2022
     */
    int insert(UserDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Jul 24 18:33:43 EDT 2022
     */
    int insertSelective(UserDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Jul 24 18:33:43 EDT 2022
     */
    UserDo selectByPrimaryKey(Integer id);

    UserDo selectByTel(String tel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Jul 24 18:33:43 EDT 2022
     */
    int updateByPrimaryKeySelective(UserDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Jul 24 18:33:43 EDT 2022
     */
    int updateByPrimaryKey(UserDo row);
}