package hz.mall.flashsale.mapper;

import hz.mall.flashsale.domain.UserPasswordDo;

public interface UserPasswordDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jul 24 18:06:00 EDT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jul 24 18:06:00 EDT 2022
     */
    int insert(UserPasswordDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jul 24 18:06:00 EDT 2022
     */
    int insertSelective(UserPasswordDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jul 24 18:06:00 EDT 2022
     */
    UserPasswordDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jul 24 18:06:00 EDT 2022
     */
    int updateByPrimaryKeySelective(UserPasswordDo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Jul 24 18:06:00 EDT 2022
     */
    int updateByPrimaryKey(UserPasswordDo row);
}