volumes:
  data:

services:

  mysql:
    image: mysql:oracle
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw
      - MYSQL_DATABASE=flash_sale
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  flash-sale-mall:
    image: hz2771/flashsale:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://root:mysqlpw@mysql:3306/flash_sale?useUnicode=true&characterEncoding=UTF-8
    restart: on-failure
